# DO NOT MODIFY ! - this file is generated by generate-packages.sh
let
    nixpkgs = import ./release.nix;

    doHaddock = nixpkgs.haskell.lib.doHaddock;
    doCoverage = nixpkgs.haskell.lib.doCoverage;
    mapAttrs = nixpkgs.lib.mapAttrs;

in mapAttrs (name: value: doHaddock (doCoverage value))
{
    inherit (nixpkgs.haskellPackages)
        package2 package1;
}
